# -*- coding: utf-8 -*-
"""odev_2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18R6J2Pv6SYTiU6rtFijL9GQ-KGoJBlq_
"""

import cv2
import numpy as np

kamera = cv2.VideoCapture(0)
while True:
    # Kameradan bir görüntü alma
    ret, frame = kamera.read()
    #  HSV renk uzayına çevirme
    hsv = cv2.cvtColor(frame, cv2.COLOR_BGR2HSV)

    #Kırmızı renk aralığını gösteriyor
    alt_kırmızı = np.array([0, 100, 100])
    üst_kırmızı = np.array([10, 255, 255])
    # Kırmızı rengi maskeliyor
    kırmızı_mask = cv2.inRange(hsv, alt_kırmızı, üst_kırmızı)

    #Yeşil renk aralığını gösteriyor
    alt_yesil = np.array([30, 30, 30])
    üst_yesil = np.array([100, 255, 255])
    # Yeşil rengi maskeliyor
    yesil_mask = cv2.inRange(hsv, alt_yesil, üst_yesil)

    #Mavi renk aralığını gösteriyor
    alt_mavi = np.array([90, 50, 50])
    üst_mavi = np.array([120, 255, 255])
    # Mavi rengi maskeliyor
    mavi_mask = cv2.inRange(hsv, alt_mavi, üst_mavi)


    # yeşil,mavi rengi siyahlaştırma yapılıyor.
    result_frame = cv2.bitwise_and(frame, frame, mask=~(yesil_mask | mavi_mask))

    # görüntünün ilk halini gösteriyor.
    cv2.imshow("İlk hali frame", frame)
    # görüntünün son halini gösteriyor.
    cv2.imshow("Sonraki hali maskelenmiş", result_frame)



    if cv2.waitKey(1) & 0xFF == ord("q"):
        break

kamera.release()
cv2.destroyAllWindows()